### ISSUE TITLE
Data download freezes

### ISSUE THREAD

**Issue by manycoding** [scrapinghub/arche#99]
Our cluster freezes on data download from 383917/5/9, probably because workers cannot be freed.
The cluster has 2 cpus, the number of workers are 4.

**Comment by manycoding** [comment]
Probably it has little to do with the number of workers. I run `get_items_with_pool` with 2 workers and got the same results. Need to double check though.
The issue was fixed after I restarted my pod, so perhaps something, like one of notebooks, held the process.

**Comment by manycoding** [comment]
```
Process ForkPoolWorker-1:
Process ForkPoolWorker-6:
Process ForkPoolWorker-5:
Process ForkPoolWorker-7:
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/opt/conda/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/opt/conda/lib/python3.7/multiprocessing/pool.py", line 110, in worker
    task = get()
  File "/opt/conda/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.7/multiprocessing/queues.py", line 351, in get
    with self._rlock:
  File "/opt/conda/lib/python3.7/multiprocessing/pool.py", line 110, in worker
    task = get()
  File "/opt/conda/lib/python3.7/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
  File "/opt/conda/lib/python3.7/multiprocessing/queues.py", line 352, in get
    res = self._reader.recv_bytes()
  File "/opt/conda/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.7/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/opt/conda/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
KeyboardInterrupt
  File "/opt/conda/lib/python3.7/multiprocessing/pool.py", line 110, in worker
    task = get()
  File "/opt/conda/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.7/multiprocessing/queues.py", line 351, in get
    with self._rlock:
  File "/opt/conda/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/opt/conda/lib/python3.7/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
  File "/opt/conda/lib/python3.7/multiprocessing/pool.py", line 110, in worker
    task = get()
  File "/opt/conda/lib/python3.7/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
KeyboardInterrupt
  File "/opt/conda/lib/python3.7/multiprocessing/queues.py", line 351, in get
    with self._rlock:
KeyboardInterrupt

---------------------------------------------------------------------------
KeyboardInterrupt                         Traceback (most recent call last)
<ipython-input-2-e6acd445fb35> in <module>
----> 1 df = Arche("2235/1396/76", count=1_000_000).source_items.df

/opt/conda/lib/python3.7/site-packages/arche/arche.py in source_items(self)
     73         if not self._source_items:
     74             self._source_items = self.get_items(
---> 75                 self.source, self.start, self.count, self.filters, self.expand
     76             )
     77         return self._source_items

/opt/conda/lib/python3.7/site-packages/arche/arche.py in get_items(source, start, count, filters, expand)
    112         elif helpers.is_job_key(source):
    113             return JobItems(
--> 114                 key=source, start=start, count=count, filters=filters, expand=expand
    115             )
    116         elif helpers.is_collection_key(source):

/opt/conda/lib/python3.7/site-packages/arche/readers/items.py in __init__(self, key, start, count, filters, expand)
    112         self.start_index: int = start
    113         self._job: Job = None
--> 114         super().__init__(key, count, filters, expand)
    115 
    116     @property

/opt/conda/lib/python3.7/site-packages/arche/readers/items.py in __init__(self, key, count, filters, expand)
     76         self.filters = filters
     77         self.expand = expand
---> 78         raw = self.fetch_data()
     79         df = pd.DataFrame(list(raw))
     80         df["_key"] = self.format_keys(df["_key"])

/opt/conda/lib/python3.7/site-packages/arche/readers/items.py in fetch_data(self)
    139             return api.get_items(self.key, self.count, self.start_index, self.filters)
    140         else:
--> 141             return api.get_items_with_pool(self.key, self.count, self.start_index)
    142 
    143     def format_keys(self, keys: pd.Series) -> pd.Series:

/opt/conda/lib/python3.7/site-packages/arche/tools/api.py in get_items_with_pool(source_key, count, start_index, workers)
    146         results = p.starmap(
    147             partial(get_items, source_key, batch_size, p_bar=tqdm),
--> 148             zip([i for i in range(start_index, start_index + count, batch_size)]),
    149         )
    150         return np.concatenate(results)

/opt/conda/lib/python3.7/multiprocessing/pool.py in starmap(self, func, iterable, chunksize)
    274         `func` and (a, b) becomes func(a, b).
    275         '''
--> 276         return self._map_async(func, iterable, starmapstar, chunksize).get()
    277 
    278     def starmap_async(self, func, iterable, chunksize=None, callback=None,

/opt/conda/lib/python3.7/multiprocessing/pool.py in get(self, timeout)
    649 
    650     def get(self, timeout=None):
--> 651         self.wait(timeout)
    652         if not self.ready():
    653             raise TimeoutError

/opt/conda/lib/python3.7/multiprocessing/pool.py in wait(self, timeout)
    646 
    647     def wait(self, timeout=None):
--> 648         self._event.wait(timeout)
    649 
    650     def get(self, timeout=None):

/opt/conda/lib/python3.7/threading.py in wait(self, timeout)
    550             signaled = self._flag
    551             if not signaled:
--> 552                 signaled = self._cond.wait(timeout)
    553             return signaled
    554 

/opt/conda/lib/python3.7/threading.py in wait(self, timeout)
    294         try:    # restore state no matter what (e.g., KeyboardInterrupt)
    295             if timeout is None:
--> 296                 waiter.acquire()
    297                 gotit = True
    298             else:

KeyboardInterrupt: 
```

**Comment by manycoding** [comment]
It's rarely reproducible, if reproducible at all. I doubt it needs any fixing.
